name: Docs Tests
on:
  push:
    branches: ['main']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      with:
        python_version: '3.7'
    - name: Install the Python dependencies
      run: |
        pip install -e .[dev,test] codecov
        pip install -r docs/doc-requirements.txt
        wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb && sudo dpkg -i pandoc-1.19.1-1-amd64.deb
    - name: List installed packages
      run: |
        pip freeze
        pip check
    - name: Run tests on documentation
      run: |
        EXIT_STATUS=0
        make -C docs/ html SPHINXOPTS="-W" || EXIT_STATUS=$?
        # Ignore warnings to work around
        # # https://github.com/computationalmodelling/nbval/issues/180
        pytest --nbval --current-env -W default docs || EXIT_STATUS=$?
        exit $EXIT_STATUS
