name: notebook_docs
channels:
  - conda-forge
dependencies:
- python=3.8
- pydata-sphinx-theme
- jinja2
- tornado
- nbformat
- jupyter_client
- ipykernel
- pip
- sphinx
- terminado
- myst-parser
- pip:
  - nbsphinx
  - Send2Trash
  - prometheus_client
  - sphinxcontrib_github_alt
