/*1)SELECT m.NOME, p.NOME
FROM MEDICO m, PACIENTE p, ATENDIMENTO a
WHERE m.CRM = a.CRM
	AND p.cpf = a.cpf;

2)SELECT P.NOME
FROM PACIENTE P, HOSPITAL H,  PLANO_DE_SAUDE PS, CREDENCIAMENTO C
WHERE P.NOME_PLANO = PS.NOME_PLANO
  AND PS.NOME_PLANO = C.NOME_PLANO
  AND C.HOSPITAL_ID = H.HOSPITAL_ID
  AND H.NOME = 'Santa Casa de Campo Mourão'
  AND P.CPF IN (SELECT P2.CPF
                FROM PACIENTE P2, MEDICO M, ATENDIMENTO A 
                WHERE M.CRM = A.CRM
                  AND A.CPF = P2.CPF);

3)SELECT PS.NOME_PLANO, COUNT(*) AS CONTAGEM_CREDENCIAIS
FROM PLANO_DE_SAUDE PS, CREDENCIAMENTO C, HOSPITAL H
WHERE PS.NOME_PLANO = C.NOME_PLANO
	AND C.HOSPITAL_ID = H.HOSPITAL_ID
	GROUP BY PS.NOME_PLANO;

4)

5)SELECT DISTINCT P.NOME
FROM MEDICO M, PACIENTE P, ATENDIMENTO A
WHERE M.CRM = A.CRM
  AND A.CPF = P.CPF
GROUP BY P.NOME
HAVING 3 < (SELECT COUNT(*) 
            FROM MEDICO M2, PACIENTE P2, ATENDIMENTO A2
            WHERE M2.CRM = A2.CRM
              AND A2.CPF = P2.CPF);
              
              
              
              
              SELECT P.NOME
FROM PACIENTE P, ATENDIMENTO A
GROUP BY A.CPF
HAVING 3 < (SELECT COUNT(*) 
            FROM MEDICO M, PACIENTE P2, ATENDIMENTO A2
            WHERE M.CRM = A2.CRM
              AND A2.CPF = P2.CPF);
6) Enviar resposta em anexo.*/

/*/*1)SELECT m.NOME, p.NOME
FROM MEDICO m, PACIENTE p, ATENDIMENTO a
WHERE m.CRM = a.CRM
	AND p.cpf = a.cpf;

2)SELECT P.NOME
FROM PACIENTE P, HOSPITAL H,  PLANO_DE_SAUDE PS, CREDENCIAMENTO C
WHERE P.NOME_PLANO = PS.NOME_PLANO
  AND PS.NOME_PLANO = C.NOME_PLANO
  AND C.HOSPITAL_ID = H.HOSPITAL_ID
  AND H.NOME = 'Santa Casa de Campo Mourão'
  AND P.CPF IN (SELECT P2.CPF
                FROM PACIENTE P2, MEDICO M, ATENDIMENTO A 
                WHERE M.CRM = A.CRM
                  AND A.CPF = P2.CPF);

3)SELECT PS.NOME_PLANO, COUNT(*) AS CONTAGEM_CREDENCIAIS
FROM PLANO_DE_SAUDE PS, CREDENCIAMENTO C, HOSPITAL H
WHERE PS.NOME_PLANO = C.NOME_PLANO
	AND C.HOSPITAL_ID = H.HOSPITAL_ID
	GROUP BY PS.NOME_PLANO;

4)SELECT H.NOME
FROM HOSPITAL H
WHERE H.HOSPITAL_ID NOT IN (SELECT H2.HOSPITAL_ID
                            FROM HOSPITAL H2, PLANO_DE_SAUDE PS, CREDENCIAMENTO C
                            WHERE H2.HOSPITAL_ID = C.HOSPITAL_ID
                              AND C.NOME_PLANO = PS.NOME_PLANO
                              AND PS.NOME_PLANO IN (SELECT PS2.NOME_PLANO
                                                    FROM PLANO_DE_SAUDE PS2, PACIENTE P, ATENDIMENTO A
                                                    WHERE PS2.NOME_PLANO = P.NOME_PLANO
                                                      AND P.CPF = A.CPF
                                                      AND A.DATA_ATENDIMENTO LIKE '%2018%'));

5)SELECT DISTINCT P.NOME
FROM MEDICO M, PACIENTE P, ATENDIMENTO A
WHERE M.CRM = A.CRM
  AND A.CPF = P.CPF
GROUP BY P.NOME
HAVING 3 < (SELECT COUNT(*) 
            FROM MEDICO M2, PACIENTE P2, ATENDIMENTO A2
            WHERE M2.CRM = A2.CRM
              AND A2.CPF = P2.CPF);

6) Resposta em anexo.         */
use prova3;


drop table if exists ATENDIMENTO;
drop table if exists CREDENCIAMENTO;

drop table if exists PACIENTE;
drop table if exists HOSPITAL;
drop table if exists MEDICO;
drop table if exists PLANO_DE_SAUDE;
CREATE TABLE HOSPITAL(
 HOSPITAL_ID INTEGER,
 NOME VARCHAR(350),
 PRIMARY KEY (HOSPITAL_ID)
);

CREATE TABLE PLANO_DE_SAUDE(
 NOME_PLANO VARCHAR(100),
 TELEFONE CHAR(9),
 PRIMARY KEY (NOME_PLANO)
);

CREATE TABLE CREDENCIAMENTO(
 NOME_PLANO VARCHAR(100),
 HOSPITAL_ID INTEGER,
 PRIMARY KEY(NOME_PLANO, HOSPITAL_ID),
 FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID),
 FOREIGN KEY (NOME_PLANO) REFERENCES PLANO_DE_SAUDE(NOME_PLANO)
);

CREATE TABLE MEDICO(  
 CRM INTEGER,
 NOME VARCHAR(300),
 PRIMARY KEY(CRM) 
);

CREATE TABLE PACIENTE(
 CPF CHAR(11) PRIMARY KEY,
 NOME VARCHAR(255),
 NOME_PLANO  VARCHAR(100),
 FOREIGN KEY (NOME_PLANO) REFERENCES PLANO_DE_SAUDE(NOME_PLANO)
);

CREATE TABLE ATENDIMENTO(
 CRM INTEGER,   
 CPF CHAR(11),
 DATA_ATENDIMENTO DATE,  
 PRIMARY KEY(CRM, CPF),
 FOREIGN KEY (CRM) REFERENCES MEDICO(CRM), 
 FOREIGN KEY (CPF) REFERENCES PACIENTE(CPF)
);
INSERT INTO MEDICO
(CRM, NOME)VALUES
(1,'Joao da Silva');

INSERT INTO PACIENTE
(CPF, NOME)VALUES
(10,'Neto');

INSERT INTO ATENDIMENTO
(CRM, CPF, DATA_ATENDIMENTO)VALUES
(1, 10, '2021-12-10');

/*CONSULTAS
Escreva em SQL uma consulta que, caso o médico tenha pacientes, liste o nome do médico e o(s) nome(s) de seu(s) paciente(s).*/
select m.NOME, p.NOME
from MEDICO m, PACIENTE p, ATENDIMENTO a
where m.CRM = a.CRM
	and p.cpf = a.cpf;
/*Escreva em SQL uma consulta para obter o nome de cada paciente que tenha um plano de saúde que atenda na ‘Santa Casa de Campo Mourão’ e que tenha sido atendido pelo médico “João da Silva”.*/
SELECT P.NOME
FROM PACIENTE P, HOSPITAL H,  PLANO_DE_SAUDE PS, CREDENCIAMENTO C
WHERE P.NOME_PLANO = PS.NOME_PLANO
  AND PS.NOME_PLANO = C.NOME_PLANO
  AND C.HOSPITAL_ID = H.HOSPITAL_ID
  AND H.NOME = 'Santa Casa de Campo Mourão'
  AND P.CPF IN (SELECT P2.CPF
                FROM PACIENTE P2, MEDICO M, ATENDIMENTO A 
                WHERE M.CRM = A.CRM
                  AND A.CPF = P2.CPF);
/*Escreva em SQL uma consulta que informe a quantidade de hospitais para cada plano de saúde.*/
SELECT PS.NOME_PLANO, COUNT(*) AS CONTAGEM_CREDENCIAIS
FROM PLANO_DE_SAUDE PS, CREDENCIAMENTO C, HOSPITAL H
WHERE PS.NOME_PLANO = C.NOME_PLANO
  AND C.HOSPITAL_ID = H.HOSPITAL_ID
GROUP BY PS.NOME_PLANO;