#include <stdio.h>
#include "hashtable_ea.h"

int* random_vector(int n, int max, int seed, THEA* TH){
    int x, aux;
    for(x=0; x<n; x++){
        aux= rand()%(max);
        THEA_Inserir(TH, aux, aux);
    }
} 

int main(){
    float alfa;
    srand(0);
    int m, n=10000, seed = 42, i;
    THEA* t;
    //---------------------------------------------------------------------------------------------------------------
    m=9973;
    alfa=n/m;
    t=THEA_Criar(m);
    int* aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=10000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=11987;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=12000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=13999;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=14000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=15991;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=16000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=17989;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=18000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=19997;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=20000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=21997;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=22000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=23993;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=24000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=25999;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=26000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=27997;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=28000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=29989;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
    printf("\n---------------------------------------------------------------------------------------------------------------\n");
    m=30000;
    alfa=n/m;
    t=THEA_Criar(m);
    aux = random_vector(n, 10*n, seed, t);
    printf("M: %d\n", m);
    printf("N: %d\n", t->ocupado);
    printf("Alfa: %.2f\n", alfa);
    printf("Custo Mal-Sucedidas: %.2f\n", THEA_TamMedioClusters(t));
    printf("Custo Bem-Sucedidas: %d\n", THEA_CustoBemSucedida(t));
    printf("Maior Cluster: %d", THEA_ClusterMaximo(t));
    free(t->TH);
    free(t);
}